# Generated by Django 3.2.3 on 2021-05-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('currentLocation', models.CharField(max_length=500)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
