# Generated by Django 3.2.3 on 2021-05-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210514_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('image_thumbnail', models.CharField(max_length=500)),
                ('image_detailed', models.CharField(max_length=500)),
            ],
        ),
    ]
